# ----------------------
#  STATUS PLUGIN CONFIG
# ----------------------

# Set colors using formatting codes "§", view all codes here: https://minecraft.wiki/w/Talk:Formatting_codes

# Join message to remind the player to set their status
enable-join-message: true
join-message: "§7Don't forget to set your status using /status !"

# Alert players when someone starts recording or streaming
enable-media-alerts: false

# Tab Server name to display in tab
enable-tab-server-name: false
tab-server-name: "§eServer Name"